"""
This type stub file was generated by pyright.
"""

from .Interfaces import SequenceIterator

"""Bio.SeqIO parser for the ABI format.

ABI is the format used by Applied Biosystem's sequencing machines to store
sequencing results.

For more details on the format specification, visit:
http://www6.appliedbiosystems.com/support/software_community/ABIF_File_Format.pdf

"""
_EXTRACT = ...
_INSTRUMENT_SPECIFIC_TAGS = ...
_BYTEFMT = ...
_HEADFMT = ...
_DIRFMT = ...
__global_tag_listing = ...
class AbiIterator(SequenceIterator):
    """Parser for Abi files."""
    def __init__(self, source, trim=...) -> None:
        """Return an iterator for the Abi file format."""
        ...
    
    def parse(self, handle):
        """Start parsing the file, and return a SeqRecord generator."""
        ...
    
    def iterate(self, handle):
        """Parse the file and generate SeqRecord objects."""
        ...
    


if __name__ == "__main__":
    ...
