name: G001
channels:
  - conda-forge
  - r
dependencies:
  - python==3.10
  - biopython==1.79
  - pip
  - black
  - python-levenshtein==0.12.2
  - click
  - pandarallel==1.6.1
  - pydantic==1.9.0
  - pyarrow==8.0.0
  - pip:
    - git+https://github.com/jwillis0720/sadie.git@91cd2f31677121eb62b63d499de12847b5c0e791#egg=sadie_antibody
