name: G001
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python==3.10
  - pip
  # Python dependencies
  - biopython==1.79
  - black
  - click
  - logomaker==0.8
  - pandarallel==1.6.1
  - pyarrow==8.0.0
  - pydantic==1.9.0
  - python-levenshtein==0.12.2
  - rich-click==1.5.2
  - scikit-learn==1.1.3
  - git-lfs
  - pip:
      - git+https://github.com/jwillis0720/sadie.git@91cd2f31677121eb62b63d499de12847b5c0e791#egg=sadie_antibody
      - git+https://github.com/jwillis0720/seaborn.git@59a5f237709124981abf835bad9eef4132255321#egg=seaborn
      - docx2pdf==0.1.8
      - PyPDF2==2.11.1
  # R itself
  - r-base==4.1.3
  # R core dependencies
  - bioconductor-cytoml>=2.6.0,<=2.10.0
  - bioconductor-flowworkspace>=4.6.0,<=4.10.0 # contains r-dplyr
  - bioconductor-ggcyto>=1.22.0,<=1.26.0
  - bioconductor-mimosa>=1.32.0,<=1.36.0
  - r-assertthat==0.2.1
  - r-arrow>=8.0.0,<=9.0.0
  - r-forcats==0.5.2
  - r-here==1.0.1
  - r-readxl==1.4.1
  # - r-dplyr # is contained in bioconductor-flowworkspace
  - r-ggrepel=0.9
  - r-janitor==2.1.0
  - r-lubridate==1.8.0
  - r-purrr==0.3.5
  - r-readr==2.1.3
  - r-remotes==2.4.2 # require(cytoqc) # https://github.com/RGLab/cytoqc # remotes::install_github("RGLab/cytoqc")
  - r-stringr==1.4.1
  - r-tidyr==1.2.1
  - r-wcorr==1.9.5
  # R colortable dependencies
  - r-cli==3.4.1 # cli
  - r-knitr==1.40 # knitr
  - r-rmarkdown==2.18 # rmarkdown
  - r-scales==1.2.1 # scales
  - r-tibble==3.1.8 # tibble
  - r-vctrs==0.5.0
  # R cytoqc dependencies
  - bioconductor-biocgenerics>=0.40.0,<=0.44.0 # BiocGenerics
  - bioconductor-flowcore==2.6.0 # FlowCore
  - bioconductor-graph==1.72.0 # graph
  - bioconductor-rgraphviz==2.38.0 # Rgraphviz
  # - bioconductor-ggcyto # ggcyto
  - r-crayon==1.5.2 # crayon
  # - r-dplyr # is contained in bioconductor-flowworkspace # dplyr
  - r-dt==0.26 # DT
  - r-htmltools==0.5.3 # htmltools
  - r-kableextra==1.3.4 # kableExtra
  # - r-knitr # knitr
  - r-ggplot2==3.4.0 # ggplot2
  - r-mass==7.3_58.1 # MASS
  # - r-purrr # purrr
  - r-shiny==1.7.3 # shiny
  # - r-tibble # tibble
