"""
This type stub file was generated by pyright.
"""

from .PDBParser import PDBParser
from .MMCIFParser import FastMMCIFParser, MMCIFParser
from .PDBList import PDBList
from .parse_pdb_header import parse_pdb_header
from .Polypeptide import CaPPBuilder, PPBuilder, is_aa, standard_aa_names
from Bio.Data.SCOPData import protein_letters_3to1
from .PDBIO import PDBIO, Select
from .mmcifio import MMCIFIO
from . import Selection
from .Superimposer import Superimposer
from .vectors import Vector, calc_angle, calc_dihedral, m2rotaxis, refmat, rotaxis, rotaxis2m, rotmat, vector_to_axis
from .StructureAlignment import StructureAlignment
from .DSSP import DSSP, make_dssp_dict
from .ResidueDepth import ResidueDepth, get_surface
from .HSExposure import ExposureCN, HSExposureCA, HSExposureCB
from .FragmentMapper import FragmentMapper
from .Dice import extract

"""Classes that deal with macromolecular crystal structures.

Includes: PDB and mmCIF parsers, a Structure class, a module to keep a local
copy of the PDB up-to-date, selective IO of PDB files, etc.

Original Author: Thomas Hamelryck.
Contributions by:
- Peter Cock
- Joe Greener
- Rob Miller
- Lenna X. Peterson
- Joao Rodrigues
- Kristian Rother
- Eric Talevich
- and many others.
"""
