"""
This type stub file was generated by pyright.
"""

"""Parse header of PDB files into a python dictionary.

Emerged from the Columba database project www.columba-db.de, original author
Kristian Rother.
"""
def parse_pdb_header(infile): # -> dict[str, str | dict[str, dict[str, str]] | bool | list[Unknown] | None]:
    """Return the header lines of a pdb file as a dictionary.

    Dictionary keys are: head, deposition_date, release_date, structure_method,
    resolution, structure_reference, journal_reference, author and
    compound.
    """
    ...

