"""
This type stub file was generated by pyright.
"""

from Bio import BiopythonWarning

"""Some Bio.PDB-specific exceptions."""
class PDBException(Exception):
    """Define class PDBException."""
    ...


class PDBConstructionException(Exception):
    """Define class PDBConstructionException."""
    ...


class PDBConstructionWarning(BiopythonWarning):
    """Define class PDBConstructionWarning."""
    ...


