"""
This type stub file was generated by pyright.
"""

"""Selection of atoms, residues, etc."""
entity_levels = ...
def uniqueify(items): # -> list[Unknown]:
    """Return a list of the unique items in the given iterable.

    Order is NOT preserved.
    """
    ...

def get_unique_parents(entity_list): # -> list[Unknown]:
    """Translate a list of entities to a list of their (unique) parents."""
    ...

def unfold_entities(entity_list, target_level): # -> list[Entity | Atom] | list[Unknown | None]:
    """Unfold entities list to a child level (e.g. residues in chain).

    Unfold a list of entities to a list of entities of another
    level.  E.g.:

    list of atoms -> list of residues
    list of modules -> list of atoms
    list of residues -> list of chains

    - entity_list - list of entities or a single entity
    - target_level - char (A, R, C, M, S)

    Note that if entity_list is an empty list, you get an empty list back:

    >>> unfold_entities([], "A")
    []

    """
    ...

if __name__ == "__main__":
    ...
