"""
This type stub file was generated by pyright.
"""

"""Superimpose two structures."""
class Superimposer:
    """Rotate/translate one set of atoms on top of another to minimize RMSD."""
    def __init__(self) -> None:
        """Initialize the class."""
        ...
    
    def set_atoms(self, fixed, moving): # -> None:
        """Prepare translation/rotation to minimize RMSD between atoms.

        Put (translate/rotate) the atoms in fixed on the atoms in
        moving, in such a way that the RMSD is minimized.

        :param fixed: list of (fixed) atoms
        :param moving: list of (moving) atoms
        :type fixed,moving: [L{Atom}, L{Atom},...]
        """
        ...
    
    def apply(self, atom_list): # -> None:
        """Rotate/translate a list of atoms."""
        ...
    


