"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Any, Callable, Dict, Iterable, Iterator
from .generic import DataType

class DataFrame:
    class Apply(DataType):
        @staticmethod
        def get_chunks(nb_workers: int, data: pd.DataFrame, **kwargs) -> Iterator[pd.DataFrame]:
            ...
        
        @staticmethod
        def work(data: pd.DataFrame, user_defined_function: Callable, user_defined_function_args: tuple, user_defined_function_kwargs: Dict[str, Any], extra: Dict[str, Any]) -> pd.DataFrame:
            ...
        
        @staticmethod
        def reduce(datas: Iterable[pd.DataFrame], extra: Dict[str, Any]) -> pd.DataFrame:
            ...
        
    
    
    class ApplyMap(DataType):
        @staticmethod
        def get_chunks(nb_workers: int, data: pd.DataFrame, **kwargs) -> Iterator[pd.DataFrame]:
            ...
        
        @staticmethod
        def work(data: pd.DataFrame, user_defined_function: Callable, user_defined_function_args: tuple, user_defined_function_kwargs: Dict[str, Any], extra: Dict[str, Any]) -> pd.DataFrame:
            ...
        
        @staticmethod
        def reduce(datas: Iterable[pd.DataFrame], extra: Dict[str, Any]) -> pd.DataFrame:
            ...
        
    
    


