"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Any, Callable, Dict, Iterable, Iterator
from pandas.core.window.rolling import Rolling
from .generic import DataType

class SeriesRolling:
    class Apply(DataType):
        @staticmethod
        def get_chunks(nb_workers: int, rolling: Rolling, **kwargs) -> Iterator[pd.Series]:
            ...
        
        @staticmethod
        def get_work_extra(data: Rolling) -> Dict[str, Any]:
            ...
        
        @staticmethod
        def work(data: pd.Series, user_defined_function: Callable, user_defined_function_args: tuple, user_defined_function_kwargs: Dict[str, Any], extra: Dict[str, Any]) -> pd.Series:
            ...
        
        @staticmethod
        def reduce(datas: Iterable[pd.Series], extra: Dict[str, Any]) -> pd.Series:
            ...
        
    
    


