"""
This type stub file was generated by pyright.
"""

import matplotlib as mpl
from .rcmod import *
from .utils import *
from .palettes import *
from .relational import *
from .regression import *
from .categorical import *
from .distributions import *
from .matrix import *
from .miscplot import *
from .axisgrid import *
from .widgets import *
from .colors import crayons, xkcd_rgb
from . import cm

_orig_rc_params = ...
__version__ = ...
