"""
This type stub file was generated by pyright.
"""

"""Algorithms to support fitting routines in seaborn plotting functions."""
def wls_confidence_interval(data, z=...): # -> tuple[float, float]:
    """Calculate the Wilson score confidence interval for a data set.

    data : array of 1-dimensional data, 1's or 0's
    z : float, z-score default=1.96 for a 95% confidence interval
    """
    ...

def bootstrap(*args, **kwargs): # -> NDArray[Unknown]:
    """Resample one or more arrays with replacement and store aggregate values.

    Positional arguments are a sequence of arrays to bootstrap along the first
    axis and pass to a summary function.

    Keyword arguments:
        n_boot : int, default 10000
            Number of iterations
        axis : int, default None
            Will pass axis to ``func`` as a keyword argument.
        units : array, default None
            Array of sampling unit IDs. When used the bootstrap resamples units
            and then observations within units instead of individual
            datapoints.
        func : string or callable, default np.mean
            Function to call on the args that are passed in. If string, tries
            to use as named method on numpy array.
        seed : Generator | SeedSequence | RandomState | int | None
            Seed for the random number generator; useful if you want
            reproducible resamples.

    Returns
    -------
    boot_dist: array
        array of bootstrapped statistic values

    """
    ...

