"""
This type stub file was generated by pyright.
"""

import pytest

def has_verdana(): # -> bool:
    """Helper to verify if Verdana font is present"""
    ...

@pytest.fixture(scope="session", autouse=True)
def remove_pandas_unit_conversion(): # -> None:
    ...

@pytest.fixture(autouse=True)
def close_figs(): # -> Generator[None, None, None]:
    ...

@pytest.fixture(autouse=True)
def random_seed(): # -> None:
    ...

@pytest.fixture()
def rng(): # -> RandomState:
    ...

@pytest.fixture
def wide_df(rng): # -> DataFrame:
    ...

@pytest.fixture
def wide_array(wide_df): # -> NDArray[Unknown]:
    ...

@pytest.fixture
def flat_series(rng): # -> TimestampSeries:
    ...

@pytest.fixture
def flat_array(flat_series): # -> NDArray[Unknown]:
    ...

@pytest.fixture
def flat_list(flat_series):
    ...

@pytest.fixture(params=["series", "array", "list"])
def flat_data(rng, request): # -> TimestampSeries | ndarray[Unknown, Unknown] | NDArray[Unknown] | list[Timestamp]:
    ...

@pytest.fixture
def wide_list_of_series(rng): # -> list[TimestampSeries]:
    ...

@pytest.fixture
def wide_list_of_arrays(wide_list_of_series): # -> list[NDArray[Unknown]]:
    ...

@pytest.fixture
def wide_list_of_lists(wide_list_of_series): # -> list[Unknown]:
    ...

@pytest.fixture
def wide_dict_of_series(wide_list_of_series): # -> dict[Unknown, Unknown]:
    ...

@pytest.fixture
def wide_dict_of_arrays(wide_list_of_series): # -> dict[Unknown, NDArray[Unknown]]:
    ...

@pytest.fixture
def wide_dict_of_lists(wide_list_of_series): # -> dict[Unknown, Unknown]:
    ...

@pytest.fixture
def long_df(rng): # -> DataFrame:
    ...

@pytest.fixture
def long_dict(long_df):
    ...

@pytest.fixture
def repeated_df(rng): # -> DataFrame:
    ...

@pytest.fixture
def missing_df(rng, long_df):
    ...

@pytest.fixture
def object_df(rng, long_df):
    ...

@pytest.fixture
def null_series(flat_series): # -> Series[Unknown]:
    ...

