"""
This type stub file was generated by pyright.
"""

__all__ = ["palplot", "dogplot"]
def palplot(pal, size=...): # -> None:
    """Plot the values in a color palette as a horizontal array.

    Parameters
    ----------
    pal : sequence of matplotlib colors
        colors, i.e. as returned by seaborn.color_palette()
    size :
        scaling factor for size of plot

    """
    ...

def dogplot(*_, **__): # -> None:
    """Who's a good boy?"""
    ...

