name: Combine
on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]

jobs:
  collate-combine:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} # this is necessary to use the shell paths that conda setups
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Env and Test
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          environment-file: environment_cross_platform.yml
          activate-environment: G001
          auto-activate-base: false
      - run: pip install -e '.[dev]'
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
      - name: Git LFS Pull
        run: |
          git lfs pull
          git lfs ls-files
      - name: Test Combine
        run: pytest -x -s --log-cli-level INFO tests/integration/test_combine_integration.py
