name: Sequence Analysis Pipeline

on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} # this is necessary to use the shell paths that ocnda setups
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('etc/example-environment.yml') }}
      - name: Setup Env and Test
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          environment-file: environment_cross_platform.yml
          activate-environment: G001
          auto-activate-base: false
      - run: |
          conda install pytest
          pip install -e .
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
      - name: Git LFS Pull
        run: |
          git lfs pull
          git lfs ls-files
      - name: Test NGS
        run: pytest -x -s --log-cli-level INFO tests/integration/test_sequence_analysis_integration.py::test_ngs_module
      - name: Test Find
        run: pytest -x -s --log-cli-level INFO tests/integration/test_sequence_analysis_integration.py::test_find_module
      - name: Test Model
        run: pytest -x -s --log-cli-level INFO tests/integration/test_sequence_analysis_integration.py::test_model_module
      - name: Test Split
        run: pytest -x -s --log-cli-level INFO tests/integration/test_sequence_analysis_integration.py::test_split_module
      - name: Test Correct
        run: pytest -x -s --log-cli-level INFO tests/integration/test_sequence_analysis_integration.py::test_correct_module
      - name: Test Join
        run: pytest -x -s --log-cli-level INFO tests/integration/test_sequence_analysis_integration.py::test_join_module
      - name: Test Annotate
        run: pytest -x -s --log-cli-level INFO tests/integration/test_sequence_analysis_integration.py::test_annotate_module
      - name: Test Tag
        run: pytest -x -s --log-cli-level INFO tests/integration/test_sequence_analysis_integration.py::test_tag_module
      - name: Test Pair
        run: pytest -x -s --log-cli-level INFO tests/integration/test_sequence_analysis_integration.py::test_pair_module
      - name: Test Unblind
        run: pytest -x -s --log-cli-level INFO tests/integration/test_sequence_analysis_integration.py::test_unblind_module
      - name: Test Personalize
        run: pytest -x -s --log-cli-level INFO tests/integration/test_sequence_analysis_integration.py::test_personalize_module
      - name: Test Mutate
        run: pytest -x -s --log-cli-level INFO tests/integration/test_sequence_analysis_integration.py::test_mutate_module
