
name: Process Flow
on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]

jobs:
  collate-combine:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} # this is necessary to use the shell paths that conda setups
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Env and Test
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          environment-file: environment_cross_platform.yml
          activate-environment: G001
          auto-activate-base: false
      - run: pip install -e '.[dev]'
      - name: Get Data
      - run: |
          wget https://iavig001public.s3.us-west-2.amazonaws.com/flow_input_sampled.tgz
          tar -xzf flow_input_sampled.tgz
      - name: Test
      - run: pytest -s -x --log-cli-level INFO tests/integration/test_flow_process_integration.py